alter table cy_article add uid int not null default 0 comment'所属用户' after cid;
alter table cy_article add recycle tinyint(1) not null default 0 comment'回收站' after status;
alter table cy_admin add group_id tinyint(1) not null default 0 COMMENT'用户分组' after path;
alter table cy_category add share tinyint(1) not null default 0 comment'会员共享' after isShow;
create table `cy_domain`(
    id int(11) not null primary key auto_increment,
    web_domain varchar(130) not null default '' comment'网站域名',
    web_logo varchar(130) not null default '' comment'网站logo',
    web_title varchar(60) not null default '' comment'标题',
    web_key varchar(100) not null default '' comment'关键字',
    web_desc varchar(200) not null default '' comment'描述',
    web_Copyright text not null default '' comment'备案信息',
    web_Copy text not null default '' comment'版权信息',
    web_footer_title varchar(350) not null default '' comment'底部标语|其他',
    view_path varchar(50) not null default '' comment'网站模板',
    createTime int not null default 0 comment'创建时间',
    updateTime int not null default 0 comment'创建时间'
)engine=myisam charset=utf8 comment='站群配置表';
alter table cy_domain add web_ico varchar(130) not null default '' comment'ico图标' after web_logo;
alter table cy_visit add guv varchar(60) not null default '' comment'访客标记uv' after ip;
CREATE TABLE `cy_collect` (
  `collect_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `collect_name` varchar(30) NOT NULL DEFAULT '' COMMENT '资源名称',
  `collect_web` varchar(160) NOT NULL DEFAULT '' COMMENT '官方网站',
  `collect_url` varchar(255) NOT NULL DEFAULT '' COMMENT '接口地址',
  `collect_type` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '接口类型',
  `collect_mid` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '资源类型',
  `collect_appid` varchar(30) NOT NULL DEFAULT '' COMMENT '',
  `collect_appkey` varchar(30) NOT NULL DEFAULT '',
  `collect_param` varchar(100) NOT NULL DEFAULT '' COMMENT '附加参数',
  `collect_filter` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '地址过滤',
  `collect_filter_from` varchar(255) NOT NULL DEFAULT '' COMMENT '过滤代码',
  `collect_filter_year` varchar(255) NOT NULL DEFAULT '' COMMENT '采集时，过滤年份',
  `collect_opt` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '数据操作',
  `collect_sync_pic_opt` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '同步图片选项，0-跟随全局，1-开启，2-关闭',
   createTime int not null default 0 COMMENT'创建时间',
   updateTime int not null default 0 COMMENT'创建时间',
  PRIMARY KEY (`collect_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `cy_vod_search` (
  `search_key` char(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '搜索键（关键词md5）',
  `search_word` varchar(128) NOT NULL COMMENT '搜索关键词',
  `search_field` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '搜索字段名（可有多个，用|分隔）',
  `search_hit_count` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '搜索命中次数',
  `search_last_hit_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最近命中时间',
  `search_update_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '添加时间',
  `search_result_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '结果Id数量',
  `search_result_ids` mediumtext CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '搜索结果Id列表，英文半角逗号分隔',
  PRIMARY KEY (`search_key`),
  KEY `search_field` (`search_field`),
  KEY `search_update_time` (`search_update_time`),
  KEY `search_hit_count` (`search_hit_count`),
  KEY `search_last_hit_time` (`search_last_hit_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='vod搜索缓存表';

CREATE TABLE `cy_vod` (
  `vod_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type_id` smallint(6) NOT NULL DEFAULT '0' COMMENT'分类id',
  `type_pid_id` smallint(6) unsigned NOT NULL DEFAULT '0' COMMENT'绑定的上级分类',
  `group_id` smallint(6) unsigned NOT NULL DEFAULT '0',
  `type_name` varchar(30) NOT NULL DEFAULT '' COMMENT'分类名',
  `vod_name` varchar(255) NOT NULL DEFAULT '' COMMENT'名称',
  `vod_sub` varchar(255) NOT NULL DEFAULT '' COMMENT'副标题',
  `vod_en` varchar(255) NOT NULL DEFAULT '' COMMENT'拼音',
  `vod_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT'审核状态，1已审核，0待审核',
  `vod_letter` char(1) NOT NULL DEFAULT '' COMMENT'首字母',
  `vod_color` varchar(6) NOT NULL DEFAULT '' COMMENT'颜色',
  `vod_tag` varchar(100) NOT NULL DEFAULT '' COMMENT'TAG标签',
  `vod_class` varchar(255) NOT NULL DEFAULT '' COMMENT'扩展分类',
  `vod_pic` varchar(1024) NOT NULL DEFAULT '' COMMENT'图片',
  `vod_pic_thumb` varchar(1024) NOT NULL DEFAULT '' COMMENT'缩略图',
  `vod_pic_slide` varchar(1024) NOT NULL DEFAULT '' COMMENT'海报图',
  `vod_pic_screenshot` text COMMENT'截图',
  `vod_actor` varchar(255) NOT NULL DEFAULT '' COMMENT'演员',
  `vod_director` varchar(255) NOT NULL DEFAULT '' COMMENT'导演',
  `vod_writer` varchar(100) NOT NULL DEFAULT '' COMMENT'编剧',
  `vod_behind` varchar(100) NOT NULL DEFAULT '' COMMENT'幕后',
  `vod_blurb` varchar(255) NOT NULL DEFAULT '' COMMENT'简介',
  `vod_remarks` varchar(100) NOT NULL DEFAULT '' COMMENT'备注',
  `vod_pubdate` varchar(100) NOT NULL DEFAULT '' COMMENT'上映日期',
  `vod_total` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'总集数',
  `vod_serial` varchar(20) NOT NULL DEFAULT '0' COMMENT'连载数',
  `vod_tv` varchar(30) NOT NULL DEFAULT '' COMMENT'电视频道',
  `vod_weekday` varchar(30) NOT NULL DEFAULT '' COMMENT'节目周期',
  `vod_area` varchar(20) NOT NULL DEFAULT '' COMMENT'地区',
  `vod_lang` varchar(10) NOT NULL DEFAULT '' COMMENT'语言',
  `vod_year` varchar(10) NOT NULL DEFAULT '' COMMENT'年份',
  `vod_version` varchar(30) NOT NULL DEFAULT '' COMMENT'资源版本',
  `vod_state` varchar(30) NOT NULL DEFAULT '' COMMENT'资源类别',
  `vod_author` varchar(60) NOT NULL DEFAULT '' COMMENT'作者',
  `vod_jumpurl` varchar(150) NOT NULL DEFAULT '' COMMENT'跳转URL',
  `vod_tpl` varchar(30) NOT NULL DEFAULT '' COMMENT'内容页模板',
  `vod_tpl_play` varchar(30) NOT NULL DEFAULT '' COMMENT'播放页模板',
  `vod_tpl_down` varchar(30) NOT NULL DEFAULT '' COMMENT'下载页模板',
  `vod_isend` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT'是否完结，1完结，0未完',
  `vod_lock` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT'0解锁，1锁定',
  `vod_level` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT'推荐标识',
  `vod_copyright` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT'版权处理，0关闭，1开启',
  `vod_points` smallint(6) unsigned NOT NULL DEFAULT '0' COMMENT'整数据积分',
  `vod_points_play` smallint(6) unsigned NOT NULL DEFAULT '0' COMMENT'播放积分',
  `vod_points_down` smallint(6) unsigned NOT NULL DEFAULT '0' COMMENT'下载积分',
  `vod_hits` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'人气',
  `vod_hits_day` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'日人气',
  `vod_hits_week` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'周人气',
  `vod_hits_month` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'月人气',
  `vod_duration` varchar(10) NOT NULL DEFAULT '' COMMENT'视频时长',
  `vod_up` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'顶',
  `vod_down` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'踩',
  `vod_score` decimal(3,1) unsigned NOT NULL DEFAULT '0.0' COMMENT'平均分',
  `vod_score_all` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'总评分',
  `vod_score_num` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT'总评次',
  `vod_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT'更新时间',
  `vod_time_add` int(10) unsigned NOT NULL DEFAULT '0' COMMENT'添加时间',
  `vod_time_hits` int(10) unsigned NOT NULL DEFAULT '0',
  `vod_time_make` int(10) unsigned NOT NULL DEFAULT '0',
  `vod_trysee` smallint(6) unsigned NOT NULL DEFAULT '0',
  `vod_douban_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT'豆瓣ID',
  `vod_douban_score` decimal(3,1) unsigned NOT NULL DEFAULT '0.0' COMMENT'豆瓣评分',
  `vod_reurl` varchar(255) NOT NULL DEFAULT '',
  `vod_rel_vod` varchar(255) NOT NULL DEFAULT '' COMMENT'关联视频',
  `vod_rel_art` varchar(255) NOT NULL DEFAULT '' COMMENT'关联文章',
  `vod_pwd` varchar(10) NOT NULL DEFAULT '' COMMENT'内容页密码',
  `vod_pwd_url` varchar(255) NOT NULL DEFAULT '' COMMENT'密码链接',
  `vod_pwd_play` varchar(10) NOT NULL DEFAULT '' COMMENT'播放页密码',
  `vod_pwd_play_url` varchar(255) NOT NULL DEFAULT '' COMMENT'密码链接',
  `vod_pwd_down` varchar(10) NOT NULL DEFAULT '' COMMENT'下载页密码',
  `vod_pwd_down_url` varchar(255) NOT NULL DEFAULT '' COMMENT'密码链接',
  `vod_content` mediumtext NOT NULL COMMENT'详情',
  `vod_play_from` varchar(255) NOT NULL DEFAULT '' COMMENT'选择播放器',
  `vod_play_server` varchar(255) NOT NULL DEFAULT '' COMMENT'选择服务器',
  `vod_play_note` varchar(255) NOT NULL DEFAULT '' COMMENT'播放备注',
  `vod_play_url` mediumtext NOT NULL default '' COMMENT'播放地址',
  `vod_down_from` varchar(255) NOT NULL DEFAULT '' COMMENT'下载地址',
  `vod_down_server` varchar(255) NOT NULL DEFAULT '' COMMENT'选择服务器',
  `vod_down_note` varchar(255) NOT NULL DEFAULT '' COMMENT'备注',
  `vod_down_url` mediumtext NOT NULL default '' COMMENT '下载地址',
  `vod_plot` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `vod_plot_name` mediumtext NOT NULL COMMENT'剧情标题',
  `vod_plot_detail` mediumtext NOT NULL,
  PRIMARY KEY (`vod_id`),
  KEY `type_id` (`type_id`) USING BTREE,
  KEY `type_pid_id` (`type_pid_id`) USING BTREE,
  KEY `vod_level` (`vod_level`) USING BTREE,
  KEY `vod_hits` (`vod_hits`) USING BTREE,
  KEY `vod_letter` (`vod_letter`) USING BTREE,
  KEY `vod_name` (`vod_name`) USING BTREE,
  KEY `vod_year` (`vod_year`) USING BTREE,
  KEY `vod_area` (`vod_area`) USING BTREE,
  KEY `vod_lang` (`vod_lang`) USING BTREE,
  KEY `vod_tag` (`vod_tag`) USING BTREE,
  KEY `vod_class` (`vod_class`) USING BTREE,
  KEY `vod_lock` (`vod_lock`) USING BTREE,
  KEY `vod_up` (`vod_up`) USING BTREE,
  KEY `vod_down` (`vod_down`) USING BTREE,
  KEY `vod_en` (`vod_en`) USING BTREE,
  KEY `vod_hits_day` (`vod_hits_day`) USING BTREE,
  KEY `vod_hits_week` (`vod_hits_week`) USING BTREE,
  KEY `vod_hits_month` (`vod_hits_month`) USING BTREE,
  KEY `vod_plot` (`vod_plot`) USING BTREE,
  KEY `vod_points_play` (`vod_points_play`) USING BTREE,
  KEY `vod_points_down` (`vod_points_down`) USING BTREE,
  KEY `group_id` (`group_id`) USING BTREE,
  KEY `vod_time_add` (`vod_time_add`) USING BTREE,
  KEY `vod_time` (`vod_time`) USING BTREE,
  KEY `vod_time_make` (`vod_time_make`) USING BTREE,
  KEY `vod_actor` (`vod_actor`) USING BTREE,
  KEY `vod_director` (`vod_director`) USING BTREE,
  KEY `vod_score_all` (`vod_score_all`) USING BTREE,
  KEY `vod_score_num` (`vod_score_num`) USING BTREE,
  KEY `vod_total` (`vod_total`) USING BTREE,
  KEY `vod_score` (`vod_score`) USING BTREE,
  KEY `vod_version` (`vod_version`),
  KEY `vod_state` (`vod_state`),
  KEY `vod_isend` (`vod_isend`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `cy_vod_repeat` (
  `id1` int(10) unsigned DEFAULT NULL,
  `name1` varchar(255) NOT NULL DEFAULT '',
  KEY `name1` (`name1`(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




