<?php 
return array (
  'kcm3u8' => 
  array (
    'status' => '1',
    'from' => 'kcm3u8',
    'show' => '快车资源',
    'des' => '快车资源',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jiexi.kczyapi.com/m3u8/?url=',
    'sort' => '10000',
    'tip' => '无需安装任何插件',
  ),
  '1080zy' => 
  array (
    'status' => '1',
    'from' => '1080zy',
    'show' => '1080资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1235',
    'tip' => '无需安装任何插件',
    'id' => '1080zy',
  ),
  'leshi' => 
  array (
    'status' => '1',
    'from' => 'leshi',
    'show' => '乐视资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1234',
    'tip' => '无需安装任何插件',
    'id' => 'leshi',
  ),
  'subm3u8' => 
  array (
    'status' => '1',
    'from' => 'subm3u8',
    'show' => '速播资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1232',
    'tip' => '无需安装任何插件',
    'id' => 'subm3u8',
  ),
  '1080zyk' => 
  array (
    'status' => '1',
    'from' => '1080zyk',
    'show' => '优质资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1231',
    'tip' => '无需安装任何插件',
    'id' => '1080zyk',
  ),
  'kcyun' => 
  array (
    'status' => '1',
    'from' => 'kcyun',
    'show' => '快车资源②',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1221',
    'tip' => '无需安装任何插件',
    'id' => 'kcyun',
  ),
  'xlm3u8' => 
  array (
    'status' => '1',
    'from' => 'xlm3u8',
    'show' => '新浪资源2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1219',
    'tip' => '无需安装任何插件',
    'id' => 'xlm3u8',
  ),
  'xlyun' => 
  array (
    'status' => '1',
    'from' => 'xlyun',
    'show' => '新浪资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1218',
    'tip' => '无需安装任何插件',
    'id' => 'xlyun',
  ),
  'gsyun' => 
  array (
    'status' => '1',
    'from' => 'gsyun',
    'show' => '光速云资源①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1215',
    'tip' => '无需安装任何插件',
    'id' => 'gsyun',
  ),
  'ptzy' => 
  array (
    'status' => '1',
    'from' => 'ptzy',
    'show' => '葡萄资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1213',
    'tip' => '无需安装任何插件',
    'id' => 'ptzy',
  ),
  'fsyun' => 
  array (
    'status' => '1',
    'from' => 'fsyun',
    'show' => '飞速云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1209',
    'tip' => '无需安装任何插件',
    'id' => 'fsyun',
  ),
  'fsm3u8' => 
  array (
    'status' => '1',
    'from' => 'fsm3u8',
    'show' => '飞速播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1208',
    'tip' => '无需安装任何插件',
    'id' => 'fsm3u8',
  ),
  'sdyun' => 
  array (
    'status' => '1',
    'from' => 'sdyun',
    'show' => '闪电云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1206',
    'tip' => '无需安装任何插件',
    'id' => 'sdyun',
  ),
  'wjyun' => 
  array (
    'status' => '1',
    'from' => 'wjyun',
    'show' => '无尽②',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1195',
    'tip' => '无需安装任何插件',
    'id' => 'wjyun',
  ),
  'hnm3u8' => 
  array (
    'status' => 1,
    'from' => 'hnm3u8',
    'show' => '红牛在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1193',
    'tip' => '无需安装任何插件',
    'id' => 'hnm3u8',
  ),
  'hnyun' => 
  array (
    'status' => '1',
    'from' => 'hnyun',
    'show' => '红牛云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1192',
    'tip' => '无需安装任何插件',
    'id' => 'hnyun',
  ),
  'tkyun' => 
  array (
    'status' => '1',
    'from' => 'tkyun',
    'show' => '天空云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1110',
    'tip' => '无需安装任何插件',
    'id' => 'tkyun',
  ),
  'nnm3u8' => 
  array (
    'status' => '1',
    'from' => 'nnm3u8',
    'show' => '牛牛在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1100',
    'tip' => '无需安装任何插件',
    'id' => 'nnm3u8',
  ),
  'cmm3u8' => 
  array (
    'status' => '1',
    'from' => 'cmm3u8',
    'show' => '草莓播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1060',
    'tip' => '无需安装任何插件',
    'id' => 'cmm3u8',
  ),
  'smzy' => 
  array (
    'status' => '1',
    'from' => 'smzy',
    'show' => '神马云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1052',
    'tip' => '无需安装任何插件',
    'id' => 'smzy',
  ),
  'okm3u8' => 
  array (
    'status' => '1',
    'from' => 'okm3u8',
    'show' => 'OK资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1050',
    'tip' => '无需安装任何插件',
    'id' => 'okm3u8',
  ),
  'kkm3u8' => 
  array (
    'status' => '1',
    'from' => 'kkm3u8',
    'show' => 'KK在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1045',
    'tip' => '无需安装任何插件',
    'id' => 'kkm3u8',
  ),
  'jsyun' => 
  array (
    'status' => '1',
    'from' => 'jsyun',
    'show' => '极速云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1043',
    'tip' => '无需安装任何插件',
    'id' => 'jsyun',
  ),
  'jsm3u8' => 
  array (
    'status' => '1',
    'from' => 'jsm3u8',
    'show' => '极速在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1042',
    'tip' => '无需安装任何插件',
    'id' => 'jsm3u8',
  ),
  'dbyun' => 
  array (
    'status' => '1',
    'from' => 'dbyun',
    'show' => '百度云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1034',
    'tip' => '无需安装任何插件',
    'id' => 'dbyun',
  ),
  'dbm3u8' => 
  array (
    'status' => '1',
    'from' => 'dbm3u8',
    'show' => '豆瓣在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1033',
    'tip' => '无需安装任何插件',
    'id' => 'dbm3u8',
  ),
  'ckm3u8' => 
  array (
    'status' => '1',
    'from' => 'ckm3u8',
    'show' => 'ck资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1028',
    'tip' => '无需安装任何插件',
    'id' => 'ckm3u8',
  ),
  'bjyun' => 
  array (
    'status' => '1',
    'from' => 'bjyun',
    'show' => '八戒云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1024',
    'tip' => '无需安装任何插件',
    'id' => 'bjyun',
  ),
  'bjm3u8' => 
  array (
    'status' => '1',
    'from' => 'bjm3u8',
    'show' => '八戒在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1023',
    'tip' => '无需安装任何插件',
    'id' => 'bjm3u8',
  ),
  'ffm3u8' => 
  array (
    'status' => '1',
    'from' => 'ffm3u8',
    'show' => '非凡播放①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'ffm3u8',
  ),
  '155m3u8' => 
  array (
    'status' => '1',
    'from' => '155m3u8',
    'show' => '155资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => '155m3u8',
  ),
  '360zy' => 
  array (
    'status' => '1',
    'from' => '360zy',
    'show' => '360资源①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => '360zy',
  ),
  'bfzym3u8' => 
  array (
    'status' => '1',
    'from' => 'bfzym3u8',
    'show' => '暴风资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'bfzym3u8',
  ),
  'dytt' => 
  array (
    'status' => '1',
    'from' => 'dytt',
    'show' => '电影天堂2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'dytt',
  ),
  'dyttm3u8' => 
  array (
    'status' => '1',
    'from' => 'dyttm3u8',
    'show' => '电影天堂1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'dyttm3u8',
  ),
  'haiwaikan' => 
  array (
    'status' => '1',
    'from' => 'haiwaikan',
    'show' => '海外看资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'haiwaikan',
  ),
  'heimuer' => 
  array (
    'status' => '1',
    'from' => 'heimuer',
    'show' => '黑木耳资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'heimuer',
  ),
  'hhm3u8' => 
  array (
    'status' => '1',
    'from' => 'hhm3u8',
    'show' => '火狐资源2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'hhm3u8',
  ),
  'kuaikan' => 
  array (
    'status' => '1',
    'from' => 'kuaikan',
    'show' => '快看资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'kuaikan',
  ),
  'kuaikanyun' => 
  array (
    'status' => '1',
    'from' => 'kuaikanyun',
    'show' => '快看云',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'kuaikanyun',
  ),
  'kuaiyun' => 
  array (
    'status' => '1',
    'from' => 'kuaiyun',
    'show' => '快云资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'kuaiyun',
  ),
  'kuaiyunbo' => 
  array (
    'status' => '1',
    'from' => 'kuaiyunbo',
    'show' => '快云资源2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'kuaiyunbo',
  ),
  'mzm3u8' => 
  array (
    'status' => '1',
    'from' => 'mzm3u8',
    'show' => '魔爪资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'mzm3u8',
  ),
  'ruyi' => 
  array (
    'status' => '1',
    'from' => 'ruyi',
    'show' => '如意资源2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'ruyi',
  ),
  'rym3u8' => 
  array (
    'status' => '1',
    'from' => 'rym3u8',
    'show' => '如意资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'rym3u8',
  ),
  'slm3u8' => 
  array (
    'status' => '1',
    'from' => 'slm3u8',
    'show' => '森林资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'slm3u8',
  ),
  'snm3u8' => 
  array (
    'status' => '1',
    'from' => 'snm3u8',
    'show' => '索尼资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'snm3u8',
  ),
  'subyun' => 
  array (
    'status' => '1',
    'from' => 'subyun',
    'show' => '速播资源2',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'subyun',
  ),
  'thm3u8' => 
  array (
    'status' => '1',
    'from' => 'thm3u8',
    'show' => '桃花资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'thm3u8',
  ),
  'yym3u8' => 
  array (
    'status' => '1',
    'from' => 'yym3u8',
    'show' => '鸭鸭资源',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'yym3u8',
  ),
  'wjm3u8' => 
  array (
    'status' => '0',
    'from' => 'wjm3u8',
    'show' => 'wjm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://jx.wujinapi.com/dplayer/?url=',
    'sort' => '222',
    'tip' => '',
    'id' => 'wjm3u8',
  ),
  'liangzi' => 
  array (
    'from' => 'liangzi',
    'show' => '量子资源站0',
    'sort' => '100',
    'status' => '1',
    'ps' => '0',
    'parse' => '',
    'des' => '支持手机电脑在线播放',
    'tip' => '无需安装任何插件',
  ),
  'lzm3u8' => 
  array (
    'from' => 'lzm3u8',
    'show' => '量子资源站1',
    'sort' => 100,
    'status' => 1,
    'ps' => 0,
    'parse' => '',
    'des' => '支持手机电脑在线播放',
    'tip' => '无需安装任何插件',
  ),
  's8m3u8' => 
  array (
    'from' => 's8m3u8',
    'show' => '杏吧资源站0',
    'sort' => 100,
    'status' => 1,
    'ps' => 0,
    'parse' => '',
    'des' => '支持手机电脑在线播放',
    'tip' => '无需安装任何插件',
  ),
  'sdm3u8' => 
  array (
    'from' => 'sdm3u8',
    'show' => '闪电资源网0',
    'sort' => 100,
    'status' => 1,
    'ps' => 0,
    'parse' => '',
    'des' => '支持手机电脑在线播放',
    'tip' => '无需安装任何插件',
  ),
  'ytm3u8' => 
  array (
    'from' => 'ytm3u8',
    'show' => '玉兔资源0',
    'sort' => 100,
    'status' => 1,
    'ps' => 0,
    'parse' => '',
    'des' => '支持手机电脑在线播放',
    'tip' => '无需安装任何插件',
  ),
);